lib/offsync_web/router.ex
defmodule OffsyncWeb.Router do
  use OffsyncWeb, :router

  import OffsyncWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {OffsyncWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", OffsyncWeb do
    pipe_through :browser

    live_session :default, on_mount: OffsyncWeb.UI.Navbar do
      live "/", Live.IndexLive
      live "/etat", Live.EtatLive
      live "/reglement", Live.ReglementLive
      live "/location", Live.LocationLive
      live "/admin", Live.AdminLive.Users
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", OffsyncWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: OffsyncWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", OffsyncWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", OffsyncWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", OffsyncWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/offsync_web/controllers/user_registration_controller.ex
defmodule OffsyncWeb.UserRegistrationController do
  use OffsyncWeb, :controller

  alias Offsync.Accounts
  alias Offsync.Accounts.User
  alias OffsyncWeb.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :edit, &1)
          )

        conn
        |> put_flash(:info, "User created successfully.")
        |> UserAuth.log_in_user(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/offsync_web/views/user_registration_view.ex
defmodule OffsyncWeb.UserRegistrationView do
  use OffsyncWeb, :view
end

lib/offsync_web/templates/user_registration/new.html.heex
<h1>S'inscrire</h1>
<p>Pour devenir membre de l'association, il te suffit de remplir le formulaire. Tu as le choix entre deux types de membres :
  <ul>
    <li>membre actif, qui te donne accès au local n'importe quand, à 45 CHF/mois</li>
    <li>membre ordinaire, qui te donne accès au local quand un membre active y est, à 20 CHF/mois</li>
  </ul>
</p>
<p>Pour plus d'informations, consulter le <%= link "règlement",to: Routes.live_path(@conn, OffsyncWeb.Live.ReglementLive) %>
et les <%= link "statuts", to: Routes.static_path(@conn, "/pdf/statuts.pdf") %> de l'association.</p>

<.form let={f} for={@changeset} action={Routes.user_registration_path(@conn, :create)}>
  <div class="mb-3">
    <%= label f, :first_name, class: "form-label"%>
    <%= text_input f, :first_name, required: true, class: "form-control #{if @changeset.action, do: "is-invalid"}" %>
    <%= error_tag f, :first_name%>
  </div>
  
  <div class="mb-3">
    <%= label f, :last_name, class: "form-label"%>
    <%= text_input f, :last_name, required: true, class: "form-control #{if @changeset.action, do: "is-invalid"}" %>
    <%= error_tag f, :last_name%>
  </div>
  
  <div class="mb-3">
    <%= label f, :email, class: "form-label"%>
    <%= email_input f, :email, required: true, class: "form-control #{if @changeset.action, do: "is-invalid"}" %>
    <%= error_tag f, :email %>
  </div>

  <div class="mb-3">
    <%= label f, :password, class: "form-label" %>
    <%= password_input f, :password, required: true , class: "form-control #{if @changeset.action, do: "is-invalid"}"%>
    <%= error_tag f, :password %>
  </div>

  <div class="mb-3">
    <%= label f, :type, class: "form-label" %>
    <%= select f, :type, ["Membre actif": :active, "Membre ordinaire": :standard], class: "form-control #{if @changeset.action, do: "is-invalid"}"%>
    <%= error_tag f, :type%>
  </div>

  <div>
    <%= submit "Devenir membre!" %>
  </div>
</.form>

<p class="mt-5">
  <%= link "Log in", to: Routes.user_session_path(@conn, :new) %> |
  <%= link "Mot de passe oublié?", to: Routes.user_reset_password_path(@conn, :new) %>
</p>